"""empty message

Revision ID: 1652c758fe1e
Revises: f8508325bec9
Create Date: 2020-06-17 12:23:05.142404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1652c758fe1e'
down_revision = 'f8508325bec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actors_name', table_name='actors')
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=True)
    op.drop_index('ix_movies_title', table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.create_index('ix_actors_name', 'actors', ['name'], unique=False)
    # ### end Alembic commands ###
