"""empty message

Revision ID: ba2945112c14
Revises:
Create Date: 2020-06-17 14:34:53.279227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2945112c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=True)
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('release_date', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    op.create_table('roles',
                    sa.Column('movie_id', sa.Integer(), nullable=True),
                    sa.Column('actor_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
                    )


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.drop_table('actors')
