"""empty message

Revision ID: f8508325bec9
Revises: a0a7d798422a
Create Date: 2020-06-16 22:11:41.156804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8508325bec9'
down_revision = 'a0a7d798422a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )
    op.drop_constraint('movies_actor_id_fkey', 'movies', type_='foreignkey')
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movies_actor_id_fkey', 'movies', 'actors', ['actor_id'], ['id'])
    op.drop_table('roles')
    # ### end Alembic commands ###
